# If this file seems strange to you, you can start with some intro: https://www.youtube.com/playlist?list=PLqq-6Pq4lTTaoaVoQVfRJPqvNTCjcTvJB

spring:
  application:
    name: app-customer-service
  profiles:
    active:
    - ${ENV:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/liquibase-master-changelog.xml
    url: ${spring.datasource.url}
    user: ${DB_OWNER_NAME}
    password: ${DB_OWNER_PASSWORD}
    parameters:
      type.date_time: timestamp
      default_date: now()
      owner_name: ${spring.liquibase.user}
      user_name: ${spring.datasource.username}

server:
  port: ${APP_PORT:9010}
  servlet:
    context-path: /${spring.application.name}

# Spring Boot Actuator
# https://youtu.be/z8kfFbfGGME?t=436
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.endava: ${ENDAVA_LOGGING_LEVEL:DEBUG}
    org.zalando.logbook: TRACE
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    console: "%d [%-16thread] %-5level [%X{traceId} / %X{spanId}] %logger{36} - %msg%n"

logbook:
  exclude:
    - ${server.servlet.context-path}/actuator/health
    - ${server.servlet.context-path}/swagger-ui/*
    - ${server.servlet.context-path}/v3/api-docs/*

application:
  name: ${spring.application.name}
  description: The implementation of the Customer Service API
  license: MIT License
  license-url: https://choosealicense.com/licenses/mit/
  contact-name: Endava
  contact-url: https://www.endava.com/en/About/Locations/Central-Europe/Timisoara
  contact-mail: developer.tmd@endava.com

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: customer
      paths-to-match: /v1/**
